import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebars:SidebarsConfig = {
  mainSidebar: [
    "getting-started",
    {
      type: "category",
      label: "User Guide",
      items: [
        {
          type: "autogenerated",
          dirName: "user-guide"
        }
      ]
    },
    {
      type: "category",
      label: "Developer",
      items: [
        {
          type: "autogenerated",
          dirName: "developer"
        }
      ]
    }
  ]
}

export default sidebars
