import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebars:SidebarsConfig = {
  mainSidebar: [
    "intro",
    "dashboards",
    "plugin-management",
    {
      type: "category",
      label: "Guides",
      items: [
        {
          type: "autogenerated",
          dirName: "guides"
        }
      ]
    }
  ]
}

export default sidebars
